# Dependabot version updates
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: 'github-actions'
    open-pull-requests-limit: 1
    directory: '/'
    schedule:
      interval: 'monthly'
    commit-message:
      prefix: 'chore(deps)'
    labels:
      - 'dependencies'
    groups:
      github-actions:
        applies-to: version-updates
        patterns:
          - '*'

  - package-ecosystem: 'npm'
    open-pull-requests-limit: 3
    directory: '/'
    schedule:
      interval: 'monthly'
    commit-message:
      prefix: 'chore(deps)'
    labels:
      - 'dependencies'
    groups:
      major:
        applies-to: version-updates
        update-types:
          - 'major'
      minor:
        applies-to: version-updates
        update-types:
          - 'minor'
      patch:
        applies-to: version-updates
        update-types:
          - 'patch'
